mock_provider "aws" {}
mock_provider "random" {}
mock_provider "tls" {}

# Two published RFC 8032 test vectors (not secrets) as the PEMs the tls provider returns for ED25519:
#   vector 1  seed 9d61b19d...7f60  public 11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo   (the first engine key, kid pulso-engine-hk1)
#   vector 2  seed 4ccd089b...a6fb  public PUAXw-hDiVqStwqnTRt-vJyYLM8uxJaMwM1V8Sr0Zgw   (the extra engine key, kid pulso-engine-hk2)
override_resource {
  target = tls_private_key.agent
  values = {
    private_key_pem = "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIJ1hsZ3v/VpguoRK9JLsLMREScVpezJpGXA7rAMcrn9g\n-----END PRIVATE KEY-----\n"
    public_key_pem  = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo=\n-----END PUBLIC KEY-----\n"
  }
}

override_resource {
  target = tls_private_key.engine_extra
  values = {
    private_key_pem = "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIEzNCJso/5banbbDRuwRTg9bijGfNaumJNqM9u1PuKb7\n-----END PRIVATE KEY-----\n"
    public_key_pem  = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAPUAXw+hDiVqStwqnTRt+vJyYLM8uxJaMwM1V8Sr0Zgw=\n-----END PUBLIC KEY-----\n"
  }
}

variables {
  name_prefix            = "pulso-hk"
  region                 = "us-east-1"
  vpc_id                 = "vpc-0123456789abcdef0"
  db_subnet_ids          = ["subnet-aaaa1111", "subnet-bbbb2222"]
  sg_db_id               = "sg-0123456789abcdef0"
  agent_services_enabled = true
}

# Engine key rotation (agent-core serve-env.md section 8, docs/agent-core-serve.md section 7): add, then mint, then retire.

run "no_rotation_by_default" {
  command = apply

  assert {
    condition     = join(",", sort(keys(output.engine_published_keys))) == "pulso-engine-hk1" && output.engine_core_kid == "pulso-engine-hk1"
    error_message = "Without rotation exactly one engine kid is published and it is the active one."
  }
  assert {
    condition     = length(tls_private_key.engine_extra) == 0
    error_message = "No extra key is generated by default."
  }
}

run "step_1_add_publishes_both_kids_and_keeps_minting_with_the_first" {
  command = apply
  variables {
    engine_extra_key_suffixes = ["hk2"]
  }

  assert {
    condition     = output.engine_published_keys["pulso-engine-hk1"] == "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo" && output.engine_published_keys["pulso-engine-hk2"] == "PUAXw-hDiVqStwqnTRt-vJyYLM8uxJaMwM1V8Sr0Zgw"
    error_message = "Both engine public keys (base64url, 32 bytes) are published."
  }
  assert {
    condition     = jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__STAFF_KEYS"])).principal_keys["pulso-engine-hk2"] == "PUAXw-hDiVqStwqnTRt-vJyYLM8uxJaMwM1V8Sr0Zgw" && contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__STAFF_KEYS"])).principal_keys), "pulso-engine-hk1") && contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__STAFF_KEYS"])).principal_keys), "cc-staff-hk1")
    error_message = "staff-keys holds the platform staff key and both engine kids."
  }
  assert {
    condition     = contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__IDENTITY_KEYS"])).principal_keys), "pulso-engine-hk2") && contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__IDENTITY_KEYS"])).principal_keys), "cc-principal-hk1")
    error_message = "identity-keys holds both engine kids too (the engine calls /v1/runs as the builder principal)."
  }
  assert {
    condition     = nonsensitive(local.generated_secrets["PULSO__PULSO_SERVICE_SEED_HEX"]) == "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60" && aws_ssm_parameter.derived["engine/pulso/PULSO_SERVICE_KID"].value == "pulso-engine-hk1"
    error_message = "Step 1 does not change what the engine mints with."
  }
}

run "step_2_mint_with_the_new_kid" {
  command = apply
  variables {
    engine_extra_key_suffixes = ["hk2"]
    engine_active_key_suffix  = "hk2"
  }

  assert {
    condition     = aws_ssm_parameter.derived["engine/pulso/PULSO_SERVICE_KID"].value == "pulso-engine-hk2" && output.engine_core_kid == "pulso-engine-hk2" && output.engine_core_public_key == "PUAXw-hDiVqStwqnTRt-vJyYLM8uxJaMwM1V8Sr0Zgw"
    error_message = "The kid and the public key follow the active suffix."
  }
  assert {
    condition     = nonsensitive(local.generated_secrets["PULSO__PULSO_SERVICE_SEED_HEX"]) == "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb"
    error_message = "The engine seed is the new key seed (64 hex)."
  }
  assert {
    condition     = length(output.engine_published_keys) == 2
    error_message = "Both kids stay published until the old one is retired."
  }
}

run "step_3_retire_the_first_key" {
  command = apply
  variables {
    engine_extra_key_suffixes = ["hk2"]
    engine_active_key_suffix  = "hk2"
    engine_retire_base_key    = true
  }

  assert {
    condition     = join(",", keys(output.engine_published_keys)) == "pulso-engine-hk2"
    error_message = "Only the new engine kid is published."
  }
  assert {
    condition     = !contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__STAFF_KEYS"])).principal_keys), "pulso-engine-hk1") && !contains(keys(jsondecode(nonsensitive(local.generated_secrets["FILES__AGENT__IDENTITY_KEYS"])).principal_keys), "pulso-engine-hk1")
    error_message = "The retired kid leaves both documents."
  }
}

run "retiring_the_key_you_still_mint_with_is_refused" {
  command = plan
  variables {
    engine_retire_base_key = true
  }
  expect_failures = [terraform_data.engine_key_rotation_guard]
}

run "the_active_suffix_must_be_a_known_key" {
  command = plan
  variables {
    engine_extra_key_suffixes = ["hk2"]
    engine_active_key_suffix  = "zz9"
  }
  expect_failures = [var.engine_active_key_suffix]
}

run "an_extra_suffix_cannot_repeat_the_first" {
  command = plan
  variables {
    engine_extra_key_suffixes = ["hk1"]
  }
  expect_failures = [var.engine_extra_key_suffixes]
}

run "rotation_never_changes_the_other_kids_or_keys" {
  command = apply
  variables {
    engine_extra_key_suffixes = ["hk2"]
  }

  assert {
    condition     = jsondecode(nonsensitive(local.generated_secrets["FILES__SUPPORT__AGENT_PRIVATE_KEYS"])).staff.kid == "cc-staff-hk1" && jsondecode(nonsensitive(local.generated_secrets["FILES__SUPPORT__AGENT_PRIVATE_KEYS"])).principal.kid == "cc-principal-hk1"
    error_message = "The platform kids are not part of the engine rotation."
  }
}

run "langfuse_keys_exist_only_with_the_forwarder" {
  command = apply

  assert {
    condition     = !contains(local.secret_keys, "LANGFUSE__LANGFUSE_PUBLIC_KEY") && !contains(keys(aws_ssm_parameter.derived), "core/langfuse/LANGFUSE_BASE_URL")
    error_message = "Off by default: no Langfuse secret key and no SSM base URL."
  }
}

run "langfuse_secret_names_and_base_url_with_the_forwarder" {
  command = apply
  variables {
    otlp_forwarder_enabled = true
  }

  assert {
    condition     = local.secret_placeholders["LANGFUSE__LANGFUSE_PUBLIC_KEY"] == "CHANGE_ME" && local.secret_placeholders["LANGFUSE__LANGFUSE_SECRET_KEY"] == "CHANGE_ME"
    error_message = "The two Langfuse project keys are placeholders to be set out of band."
  }
  assert {
    condition     = aws_ssm_parameter.derived["core/langfuse/LANGFUSE_BASE_URL"].value == "https://us.cloud.langfuse.com" && aws_ssm_parameter.derived["engine/langfuse/LANGFUSE_BASE_URL"].value == "https://us.cloud.langfuse.com"
    error_message = "The base URL is not secret: SSM, per host slice."
  }
  assert {
    condition     = !contains(local.secret_keys, "LANGFUSE__LANGFUSE_BASE_URL")
    error_message = "The base URL never goes into the secret."
  }
}

run "langfuse_base_url_must_be_https" {
  command = plan
  variables {
    otlp_forwarder_enabled = true
    langfuse_base_url      = "http://langfuse.example"
  }
  expect_failures = [var.langfuse_base_url]
}
