# Credentials generated by Terraform (random_password / tls_private_key / random_bytes), like origin_verify. They are written
# once into the single secret at creation; the secret version ignores later changes (secrets.tf), so an apply never rotates
# them and out-of-band values are never overwritten. Nothing here is an output except public keys and key ids.
# Why: the shared Core is agent-core's own `agentcore serve` (agent_services_enabled, ADR 0009). It verifies Ed25519 credentials against two public
# key files (--identity-keys for /v1/runs, --staff-keys for /v1/registry and /v1/export), the platform signs with its own
# keys, the engine signs as the non-human `builder` principal, and the llm-gateway authenticates every consumer by token.

locals {
  # Ed25519 DER encodings are fixed: SPKI = 12-byte prefix + 32-byte key (12 bytes = 16 base64 chars, so the key is a plain
  # substring), PKCS#8 = 16-byte prefix + 32-byte seed (offset 128 bits: regrouped bit by bit below). Everything is pure
  # HCL on the provider's PEM attributes; docs/secrets-keys.md explains how to check the result.
  b64_alphabet = split("", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
  url_alphabet = split("", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")

  agent_key_roles = toset(["engine", "principal", "delegation", "staff"])

  # Every Ed25519 key: the four roles plus the engine's extra rotation keys (engine_<suffix>), see engine_extra_key_suffixes.
  all_agent_tls = merge(tls_private_key.agent, { for s, k in tls_private_key.engine_extra : "engine_${s}" => k })

  agent_keys = {
    for role, k in local.all_agent_tls : role => {
      public_b64url = replace(replace(substr(replace(k.public_key_pem, "/-----[A-Z ]+-----|[[:space:]]/", ""), 16, 43), "+", "-"), "/", "_")
      seed_bits     = "${substr(join("", [for c in split("", replace(k.private_key_pem, "/-----[A-Z ]+-----|[[:space:]]/", "")) : format("%06b", index(local.b64_alphabet, c))]), 128, 256)}00"
    }
  }
  # The engine reads its service seed as 64 hex characters (PULSO_SERVICE_SEED_HEX): regroup the same 256 seed bits by four.
  agent_seeds_hex = {
    for role, k in local.agent_keys : role => join("", [
      for i in range(64) : format("%x", sum([for j in range(4) : tonumber(substr(k.seed_bits, i * 4 + j, 1)) * pow(2, 3 - j)]))
    ])
  }
  agent_seeds = {
    for role, k in local.agent_keys : role => join("", [
      for i in range(43) : local.url_alphabet[sum([for j in range(6) : tonumber(substr(k.seed_bits, i * 6 + j, 1)) * pow(2, 5 - j)])]
    ])
  }

  # Engine key rotation (agent-core docs/serve-env.md section 8, docs/agent-core-serve.md): the key generated first has kid
  # pulso-engine-<agent_keys_suffix> (role "engine"); engine_extra_key_suffixes adds keys pulso-engine-<suffix> beside it. EVERY listed
  # kid is published in identity-keys and staff-keys (serve reloads the files, no restart); only the ACTIVE one is minted with
  # (PULSO_SERVICE_KID and PULSO_SERVICE_SEED_HEX). engine_retire_base_key drops the first key from the documents.
  engine_active_suffix = coalesce(var.engine_active_key_suffix, var.agent_keys_suffix)
  engine_active_id     = local.engine_active_suffix == var.agent_keys_suffix ? "engine" : "engine_${local.engine_active_suffix}"
  engine_kid           = "pulso-engine-${local.engine_active_suffix}"
  engine_published = merge(
    var.engine_retire_base_key ? {} : { "pulso-engine-${var.agent_keys_suffix}" = "engine" },
    { for s in var.engine_extra_key_suffixes : "pulso-engine-${s}" => "engine_${s}" },
  )
  engine_published_public = { for kid, id in local.engine_published : kid => local.agent_keys[id].public_b64url }
  principal_kid           = "cc-principal-${var.agent_keys_suffix}"
  delegation_kid          = "cc-grant-${var.agent_keys_suffix}"
  staff_kid               = "cc-staff-${var.agent_keys_suffix}"

  # agent-core `--identity-keys` (principal credentials of /v1/runs and delegations): the platform's principal and delegation
  # keys plus the engine's key (it calls /v1/runs as `builder`).
  core_identity_keys = jsonencode({
    principal_keys  = merge({ (local.principal_kid) = local.agent_keys["principal"].public_b64url }, local.engine_published_public)
    delegation_keys = { (local.delegation_kid) = local.agent_keys["delegation"].public_b64url }
  })
  # agent-core `--staff-keys` (registry API and export): the platform's staff key plus the engine's key. TRUST: the Core checks
  # the roles claimed INSIDE the credential, not a per-kid ceiling, so any key in this file can claim any role (including
  # aprobador/human). The engine key is therefore a trust grant; the engine itself never signs approve/publish/promote.
  core_staff_keys = jsonencode({
    principal_keys = merge({ (local.staff_kid) = local.agent_keys["staff"].public_b64url }, local.engine_published_public)
  })
  # The platform's private seeds (`CC_AGENT_KEYS_FILE`; same shape as gen_agent_keys.py private.json).
  platform_agent_keys = jsonencode({
    principal  = { kid = local.principal_kid, seed = local.agent_seeds["principal"] }
    delegation = { kid = local.delegation_kid, seed = local.agent_seeds["delegation"] }
    staff      = { kid = local.staff_kid, seed = local.agent_seeds["staff"] }
  })

  # Names are main's (docs/agent-services.md, docs/secrets-keys.md). Agent-services keys exist only with agent_services_enabled.
  generated_secrets = merge(
    { for c, p in random_password.gateway_token : "GATEWAY__GATEWAY_TOKEN_${c}" => p.result },
    {
      # The same value in the service that issues it (GATEWAY__) and in the one that presents it.
      "CORE__AGENTCORE_LLM_GATEWAY_TOKEN" = random_password.gateway_token["AGENT_CORE"].result
      "PULSO__PULSO_LLM_GATEWAY_KEY"      = random_password.gateway_token["ENGINE"].result
      # The engine's Ed25519 seed as the 64 hex characters the engine reads; its kid is the SSM value PULSO_SERVICE_KID.
      "PULSO__PULSO_SERVICE_SEED_HEX" = local.agent_seeds_hex[local.engine_active_id]
      # `pulso run` on a non-loopback bind exits 2 without two DIFFERENT bearer tokens of at least 24 characters.
      "PULSO__PULSO_DEBUG_TOKEN" = random_password.engine_debug.result
      "PULSO__PULSO_ADMIN_TOKEN" = random_password.engine_admin.result
    },
    var.agent_services_enabled ? {
      "AGENT__AGENTCORE_LLM_GATEWAY_TOKEN" = random_password.gateway_token["AGENT_SERVE"].result
      "AGENT__AGENTCORE_GRANTS_TOKEN"      = random_password.internal_service.result
      "SUPPORT__CC_INTERNAL_SERVICE_TOKEN" = random_password.internal_service.result
      # The engine announces proposals to the platform (POST /api/v1/internal/builder/proposals/announce) with the same bearer:
      # the platform has one service token today (CC_INTERNAL_SERVICE_TOKEN). Ask: one token per consumer (docs/shared-postgres.md).
      "PULSO__PULSO_PLATFORM_SERVICE_TOKEN" = random_password.internal_service.result
      "AGENT__AGENTCORE_KEYS_FINGERPRINT"   = "k1:${random_bytes.keys_fingerprint.base64}"
      "AGENT__AGENTCORE_KEYS_TOKEN_MAP"     = "k1:${random_bytes.keys_token_map.base64}"
      "AGENT__AGENTCORE_TOOL_SERVICE_TOKEN" = random_password.tool_service.result
      "TOOLS__TOOL_SERVICE_TOKENS"          = "agent-core:${random_password.tool_service.result}"
      # Key documents: single-line JSON written as files by the start script (FILES__<SVC>__<NAME>, docs/agent-services.md).
      "FILES__AGENT__IDENTITY_KEYS"        = local.core_identity_keys
      "FILES__AGENT__STAFF_KEYS"           = local.core_staff_keys
      "FILES__SUPPORT__AGENT_PRIVATE_KEYS" = local.platform_agent_keys
    } : {},
  )
}

resource "tls_private_key" "agent" {
  for_each  = local.agent_key_roles
  algorithm = "ED25519"
}

# Extra engine keys for rotation (empty by default). Never rotates by itself: the secret version ignores later changes, so a new key
# reaches the hosts only through the documented merge (docs/agent-core-serve.md section 5).
resource "tls_private_key" "engine_extra" {
  for_each  = toset(var.engine_extra_key_suffixes)
  algorithm = "ED25519"
}

# Fail closed on a rotation state the Core cannot serve (the active kid must be published).
resource "terraform_data" "engine_key_rotation_guard" {
  lifecycle {
    precondition {
      condition     = contains(keys(local.engine_published), local.engine_kid)
      error_message = "The active engine kid must be one of the published kids: engine_active_key_suffix is retired or unknown."
    }
  }
}

resource "random_password" "gateway_token" {
  for_each = toset(var.gateway_consumers)
  length   = 48
  special  = false
}

# Engine debug API and admin append bearer tokens (PULSO_DEBUG_TOKEN, PULSO_ADMIN_TOKEN): distinct, 48 characters.
resource "random_password" "engine_debug" {
  length  = 48
  special = false
}

resource "random_password" "engine_admin" {
  length  = 48
  special = false
}

# Bearer of consumer `agent-core` in tool-service (TOOLS__TOOL_SERVICE_TOKENS) and in agent-core's AGENTCORE_TOOL_SERVICE_TOKEN.
resource "random_password" "tool_service" {
  length  = 48
  special = false
}

# Bearer shared by agent-core's grant_active check (AGENTCORE_GRANTS_TOKEN) and the platform's /api/v1/internal routes.
resource "random_password" "internal_service" {
  length  = 48
  special = false
}

# agent-core EnvKeyProvider keys (HMAC fingerprint and token map): `kid:base64`, at least 32 bytes.
resource "random_bytes" "keys_fingerprint" {
  length = 32
}

resource "random_bytes" "keys_token_map" {
  length = 32
}
